spring.application.name=semiproject

cors.allowed-origins=${CORS_ORIGINS:http://localhost:5173}

spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.jdbc-url=jdbc:mysql://localhost:3306/cloud?serverTimezone=UTC&characterEncoding=UTF-8
# TODO [배포] jdbc-url을 RDS 엔드포인트로 변경
# spring.datasource.hikari.jdbc-url=jdbc:mysql://<RDS엔드포인트>:3306/cloud?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.hikari.username=root
spring.datasource.hikari.password=${DB_PASSWORD}
spring.datasource.hikari.auto-commit=true

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/sql-*.xml
logging.level.org.cloud.mapper=debug

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

api.recipe.key=${RECIPE_API_KEY}
mybatis.mapper-locations=classpath:mapper/sql-*.xml
logging.level.org.cloud.mapper=debug
spring.datasource.hikari.auto-commit=true
google.gemini.api.key=${GEMINI_API_KEY}
google.gemini.model.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent
spring.thymeleaf.check-template-location=false

# 파일 서빙 base URL
# file.base-url=http://localhost:8080
file.base-url=https://jooyoung-s3-finalproject-hinsher.s3.ap-northeast-2.amazonaws.com

# AWS S3
cloud.aws.s3.bucket=${S3_BUCKET_NAME}
cloud.aws.region.static=ap-northeast-2
cloud.aws.stack.auto=false
